### ISSUE TITLE
Model Management - Increase Candle per day

### ISSUE THREAD

**Issue by gsta75** [DeanAyalon/wix-hanukkan#6]
We need a model management.
Challenge: 
- During the holidays each day another candle is added to the model.
- Users are in different time ones

Possible solution:
- write code that reads the location of the user and identifies the timezone / or which reads the device time and date of the user
- identify which day it is and load a a new model URL.

In order to be cost efficient and not have 8 models of the same hanukkiah only with different amounts of candles, I suggest that we make two versions of each model: one which is live now (A) and one which is for tomorrow (B). Once the first one becomes globally yesterday then we update the model and add another candle for tomorrow

That means 2 links and during the holidays we will update the models which are all prepared beforehand.
If we have too many models, then we can also make 3 models and links to allow more update time

**Comment by DeanAyalon** [comment]
Using [SwiftXR](https://swiftxr.io) for model storage
Check for alternatives

**Comment by DeanAyalon** [comment]
So:
- Models will be manually changed every day of Hanukkah
- Site will recognize visitor's date and assign the "today"/"tomorrow" model URLs to the iFrame
